# Use a base Node.js image
FROM node:18-alpine AS base

# Set the working directory inside the container
WORKDIR /app

# Copy all files (before npm install, because volume will replace this anyway)
COPY . .

# Install deps inside the mounted volume (node_modules stays accessible)
RUN npm install

# Build the Next.js application for production
# RUN npm run build

# Expose the port Next.js runs on (default is 3000)
EXPOSE 3000

# Command to start the Next.js application in production mode
CMD ["npm", "run", "dev"]