# Set base image
FROM node:18-alpine

# Set working dir
WORKDIR /app

# Copy only dependency files first
COPY package*.json ./

# Install deps with lock file
RUN npm install

# Copy the rest of the application
COPY . .

# Expose port
EXPOSE 3000

# Start app
CMD ["npm", "run", "dev"]
