# Use a base Node.js image
FROM node:18-alpine 

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Build the Next.js application for production
# RUN npm run build

# Expose the port Next.js runs on (default is 3000)
EXPOSE 3000

# Command to start the Next.js application in production mode
CMD ["npm", "run", "dev"]