import { PrismaClient } from '@/generated/prisma';

const prisma = new PrismaClient();

export async function seedProductCategories() {
  await prisma.product_categories.createMany({
    data: [
      // Product 1: RODIM R1
      { product_id: 1, category_id: 1, value_1: '≥7.0mil', value_2: 'GBT/29061', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 2, value_1: '≥93', value_2: 'GB8807', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 3, value_1: '≤2%', value_2: 'ASTM D1003', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 4, value_1: '≥300, ≤450', value_2: 'ASTM D-882', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 5, value_1: '≥100%', value_2: 'ASTM D-882', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 6, value_1: '15≤F≤25', value_2: 'FINAT3', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 7, value_1: '20≤F≤35', value_2: 'FINAT3', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 8, value_1: '>79,<90', value_2: 'GB/T 30693-2014', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 9, value_1: '≥93%', value_2: 'GB/T 2680', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 10, value_1: 'Slight residue', value_2: 'Marker pen – wipe with alcohol after air drying', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 11, value_1: 'No scratch', value_2: '10 scrapes of a 200g/cm² loadbearing thin copper brush', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 12, value_1: '≤ 5S', value_2: '10 scrapes of a 200g/cm² loadbearing thin copper brush Can be repaired with 70°Chot water or hot-blast air', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 13, value_1: 'ΔE≤2\nNo breaks\nNo bubbles', value_2: 'QUV ≥ 2400 hours', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 14, value_1: 'Normal', value_2: 'Soak in HCl (pH 2-3) and NaOH (pH13-14) solution for 30 minutes', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 16, value_1: 'Traceless', value_2: 'Affix the product to a painted board and expose on a rooftop for 15 days then wash with water', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 1, category_id: 17, value_1: '7 years after installation', value_2: null, created_by: 1, updated_by: 1, status: 1 },

      // Product 2: RODIM R2 Matte
      { product_id: 2, category_id: 1, value_1: '≥7.5mil', value_2: 'GBT/29061', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 2, value_1: '20±2', value_2: 'GB8807', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 3, value_1: '≤2%', value_2: 'ASTM D1003', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 4, value_1: '≥300, ≤450', value_2: 'ASTM D-882', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 5, value_1: '≥100%', value_2: 'ASTM D-882', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 6, value_1: '15≤F≤25', value_2: 'FINAT3', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 7, value_1: '20≤F≤35', value_2: 'FINAT3', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 8, value_1: '>79,<90', value_2: 'GB/T 30693-2014', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 9, value_1: '≥93%', value_2: 'GB/T 2680', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 10, value_1: 'Slight residue', value_2: 'Marker pen – wipe with alcohol after air drying', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 11, value_1: 'No scratch', value_2: '10 scrapes of a 200g/cm² loadbearing thin copper brush', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 12, value_1: '≤ 5S', value_2: '10 scrapes of a 200g/cm² loadbearing thin copper brush Can be repaired with 70°Chot water or hot-blast air', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 13, value_1: 'ΔE≤2\nNo breaks\nNo bubbles', value_2: 'QUV ≥ 2800 hours', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 14, value_1: 'Normal', value_2: 'Soak in HCl (pH 2-3) and NaOH (pH13-14) solution for 30 minutes', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 16, value_1: 'Traceless', value_2: 'Affix the product to a painted board and expose on a rooftop for 15 days then wash with water', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 2, category_id: 17, value_1: '10 years after installation', value_2: null, created_by: 1, updated_by: 1, status: 1 },
      
      // Product 3: RODIM R2 PRO
      { product_id: 3, category_id: 1, value_1: '≥7.5mil', value_2: 'GBT/29061', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 2, value_1: '≥93', value_2: 'GB8807', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 3, value_1: '≤2%', value_2: 'ASTM D1003', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 4, value_1: '≥180, ≤280', value_2: 'ASTM D-882', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 5, value_1: '≥100%', value_2: 'ASTM D-882', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 6, value_1: '15≤F≤20', value_2: 'FINAT3', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 7, value_1: '20≤F≤30', value_2: 'FINAT3', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 8, value_1: '>79,<90', value_2: 'GB/T 30693-2014', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 9, value_1: '≥93%', value_2: 'GB/T 2680', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 10, value_1: 'Slight residue', value_2: 'Marker pen – wipe with alcohol after air drying', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 11, value_1: 'No scratch', value_2: '10 scrapes of a 200g/cm² loadbearing thin copper brush', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 12, value_1: '≤ 5S', value_2: '10 scrapes of a 200g/cm² loadbearing thin copper brush Can be repaired with 70°Chot water or hot-blast air', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 13, value_1: 'ΔE≤2\nNo breaks\nNo bubbles', value_2: 'QUV ≥ 2800 hours', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 14, value_1: 'Normal', value_2: 'Soak in HCl (pH 2-3) and NaOH (pH13-14) solution for 30 minutes', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 16, value_1: 'Traceless', value_2: 'Affix the product to a painted board and expose on a rooftop for 15 days then wash with water', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 3, category_id: 17, value_1: '10 years after installation', value_2: null, created_by: 1, updated_by: 1, status: 1 },
      
      // Product 4: RODIM R3 PRO
      { product_id: 4, category_id: 1, value_1: '≥8.5mil', value_2: 'GBT/29061', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 2, value_1: '≥93', value_2: 'GB8807', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 3, value_1: '≤2%', value_2: 'ASTM D1003', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 4, value_1: '≥180, ≤280', value_2: 'ASTM D-882', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 5, value_1: '≥100%', value_2: 'ASTM D-882', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 6, value_1: '15≤F≤20', value_2: 'FINAT3', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 7, value_1: '20≤F≤30', value_2: 'FINAT3', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 8, value_1: '>79,<90', value_2: 'GB/T 30693-2014', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 9, value_1: '≥93%', value_2: 'GB/T 2680', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 10, value_1: 'Slight residue', value_2: 'Marker pen – wipe with alcohol after air drying', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 11, value_1: 'No scratch', value_2: '10 scrapes of a 400g/cm² loadbearing thin copper brush', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 12, value_1: '≤ 5S', value_2: '10 scrapes of a 400g/cm² loadbearing thin copper brush Can be repaired with 70°Chot water or hot-blast air', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 13, value_1: 'ΔE≤1.5\nNo breaks\nNo bubbles', value_2: 'QUV ≥ 3200 hours', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 14, value_1: 'Normal', value_2: 'Soak in HCl (pH 2-3) and NaOH (pH13-14) solution for 30 minutes', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 15, value_1: 'No fog within 2 minutes', value_2: 'Affix the product to a painted board and spray with detergent', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 16, value_1: 'Traceless', value_2: 'Affix the product to a painted board and expose on a rooftop for 15 days then wash with water', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 4, category_id: 17, value_1: '10 years after installation', value_2: null, created_by: 1, updated_by: 1, status: 1 },

      // Product 5: RODIM R4 PRO
      { product_id: 5, category_id: 1, value_1: '≥9.5mil', value_2: 'GBT/29061', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 2, value_1: '≥93', value_2: 'GB8807', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 3, value_1: '≤2%', value_2: 'ASTM D1003', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 4, value_1: '≥180, ≤280', value_2: 'ASTM D-882', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 5, value_1: '≥100%', value_2: 'ASTM D-882', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 6, value_1: '15≤F≤20', value_2: 'FINAT3', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 7, value_1: '20≤F≤30', value_2: 'FINAT3', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 8, value_1: '>79,<90', value_2: 'GB/T 30693-2014', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 9, value_1: '≥93%', value_2: 'GB/T 2680', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 10, value_1: 'Slight residue', value_2: 'Marker pen – wipe with alcohol after air drying', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 11, value_1: 'No scratch', value_2: '10 scrapes of a 400g/cm² loadbearing thin copper brush', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 12, value_1: '≤ 5S', value_2: '10 scrapes of a 400g/cm² loadbearing thin copper brush Can be repaired with 70°Chot water or hot-blast air', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 13, value_1: 'ΔE≤1.5\nNo breaks\nNo bubbles', value_2: 'QUV ≥ 3200 hours', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 14, value_1: 'Normal', value_2: 'Soak in HCl (pH 2-3) and NaOH (pH13-14) solution for 30 minutes', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 15, value_1: 'No fog within 2 minutes', value_2: 'Affix the product to a painted board and spray with detergent', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 16, value_1: 'Traceless', value_2: 'Affix the product to a painted board and expose on a rooftop for 15 days then wash with water', created_by: 1, updated_by: 1, status: 1 },
      { product_id: 5, category_id: 17, value_1: '10 years after installation', value_2: null, created_by: 1, updated_by: 1, status: 1 },
    ],
  });
}